CREATE TABLE `profile_traveler` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '姓名',
  `card_no` varchar(20) NOT NULL DEFAULT '' COMMENT '身份证',
  `descriot` varchar(20) NOT NULL DEFAULT '',
  `ctftp` varchar(20) NOT NULL DEFAULT '',
  `ctfid` varchar(40) NOT NULL DEFAULT '',
  `gender` varchar(10) NOT NULL DEFAULT '' COMMENT '性别',
  `birthday` varchar(10) NOT NULL DEFAULT '' COMMENT '出生日期',
  `address` varchar(200) NOT NULL DEFAULT '',
  `zip` varchar(10) NOT NULL DEFAULT '' COMMENT '邮编',
  `dirty` varchar(20) NOT NULL DEFAULT '',
  `district1` varchar(50) NOT NULL DEFAULT '',
  `district2` varchar(50) NOT NULL DEFAULT '',
  `district3` varchar(50) NOT NULL,
  `district4` varchar(50) NOT NULL DEFAULT '',
  `district5` varchar(50) NOT NULL DEFAULT '',
  `district6` varchar(50) NOT NULL DEFAULT '',
  `firstnm` varchar(20) NOT NULL,
  `lastnm` varchar(50) NOT NULL DEFAULT '',
  `duty` varchar(20) NOT NULL,
  `mobile` varchar(50) NOT NULL DEFAULT '' COMMENT '手机号',
  `tel` varchar(30) NOT NULL DEFAULT '' COMMENT '固话',
  `fax` varchar(20) NOT NULL DEFAULT '' COMMENT '传真',
  `email` varchar(50) NOT NULL DEFAULT '',
  `nation` varchar(50) NOT NULL DEFAULT '',
  `taste` varchar(20) NOT NULL DEFAULT '',
  `education` varchar(20) NOT NULL,
  `company` varchar(30) NOT NULL DEFAULT '',
  `ctel` varchar(20) NOT NULL DEFAULT '',
  `caddress` varchar(50) NOT NULL DEFAULT '',
  `czip` varchar(10) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=2670 DEFAULT CHARSET=utf8;

